H = 5000; %Wysokość w m
T_0 = 288.15; %Temperatura na poziomie morza w K
p_0 = 101325; %Ciśnienie na poziomie morza k Pa
T_H = T_0 - 6.5*H/1000;
p_H = p_0*(1-H/44300)^5.256;
Ma = 0.5; %Liczba Macha
kappa = 1.4;
R = 288;
c_H = Ma*sqrt(R*kappa*T_H);
kappa_sp = 1.33;
sigma_wl = 0.95; %Sprawność wlotu
eta_ts = 0.8; %Sprawność efektywna sprężarki (zależna od prędkości)
pi_c_nom = 5.8; %Spręż sprężarki
cp = 1005;
cp_sp = 1152;
m_p_max = 0.1; % Maksymalny Strumień paliwa
W = 43*10^6; %Wartość opałowa nafty lotniczej
pi_ks = 0.95; %Współczynnik spadku ciśnienia w komorz spalania
delta_pw = 1; %Współczynnik strat mechanicznych
m_dot_nom = 4.5; %Strumień powietrza
pi_t = 2.5; %Spadek ciśnienia w turbinie
eta_tt = 1; %Sprawność efektywna turbiny
pi_d = 1.5; %Rozporządzalny spadek ciśnienia w dyszy wylotowej
pi_d_kr = 1.851; %Krytyczny spadek ciśnienia w dyszy wylotowej
phi_d = 0.98; %Sprawność dyszy
sigma_rw = 1; %Współczynnik strat ciśnienia całkowitego w rurze wylotowej
J = 5; %Moment bezwładności
n_nom = 41000; %Nominalna prędkość obrotowa wału
A_8 = 0.07; %Powierzchnia dyszy wylotowej
eta_t_nom = 0.84;
eta_c_nom = 0.78;